/**
 * Runtime permission helpers for the API.
 * Value imports from @laam/types break the Nest webpack rootDir — keep helpers local.
 */
import type { Permission, UserRole } from '@laam/types';

const PERMISSION_CATALOG = [
  'dashboard.view',
  'dashboard.widget.revenue',
  'dashboard.widget.orders',
  'dashboard.widget.leads',
  'dashboard.widget.team',
  'dashboard.widget.marketing',
  'dashboard.widget.platform',
  'contacts.view',
  'contacts.create',
  'contacts.edit',
  'contacts.delete',
  'companies.view',
  'companies.create',
  'companies.edit',
  'companies.delete',
  'leads.view',
  'leads.create',
  'leads.edit',
  'leads.assign',
  'leads.convert',
  'leads.export',
  'deals.view',
  'deals.create',
  'deals.edit',
  'deals.delete',
  'pipeline.view',
  'orders.view',
  'orders.create',
  'orders.confirm',
  'orders.cancel',
  'orders.assign',
  'orders.export',
  'campaigns.view',
  'campaigns.create',
  'campaigns.edit',
  'campaigns.manage_budget',
  'incentive.view',
  'incentive.manage',
  'tasks.view',
  'tasks.create',
  'tasks.edit',
  'tasks.assign',
  'activities.view',
  'activities.create',
  'activities.edit',
  'inventory.view',
  'inventory.create',
  'inventory.edit',
  'inventory.adjust',
  'inventory.delete',
  'inventory.purchase',
  'inventory.export',
  'inventory.warehouses',
  'inventory.mixer',
  'accounting.view',
  'accounting.create',
  'accounting.edit',
  'accounting.export',
  'accounting.manage',
  'reports.view',
  'reports.export',
  'users.view',
  'users.invite',
  'users.manage',
  'roles.view',
  'roles.manage',
  'settings.view',
  'settings.manage',
  'brand.view',
  'brand.manage',
  'billing.view',
  'billing.manage',
  'security.view',
  'security.manage',
  'courier.view',
  'courier.manage',
  'support.view',
  'support.create',
  'support.manage',
  'coupons.view',
  'coupons.manage',
  'recycle.view',
  'recycle.manage',
  'knowledge.view',
  'knowledge.manage',
  'notifications.view',
  'notifications.failed_login',
  'notifications.system',
  'notifications.low_stock',
  'notifications.overdue_followup',
  'notifications.courier_update',
  'notifications.ticket',
  'notifications.payment_due',
  'platform.view',
  'platform.manage',
  'permissions.manage',
] as const satisfies readonly Permission[];

const TENANT_PERMISSIONS = PERMISSION_CATALOG.filter(
  (p) => !p.startsWith('platform.') && p !== 'dashboard.widget.platform',
);

const ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  super_admin: [
    'dashboard.view',
    'dashboard.widget.platform',
    'dashboard.widget.revenue',
    'dashboard.widget.orders',
    'dashboard.widget.leads',
    'dashboard.widget.team',
    'dashboard.widget.marketing',
    'reports.view',
    'reports.export',
    'users.view',
    'users.manage',
    'platform.view',
    'platform.manage',
    'roles.view',
    'roles.manage',
    'permissions.manage',
  ],
  org_admin: [...TENANT_PERMISSIONS],
  ceo: [
    'dashboard.view',
    'dashboard.widget.revenue',
    'dashboard.widget.orders',
    'dashboard.widget.leads',
    'dashboard.widget.team',
    'dashboard.widget.marketing',
    'contacts.view',
    'companies.view',
    'leads.view',
    'leads.export',
    'deals.view',
    'pipeline.view',
    'orders.view',
    'orders.export',
    'campaigns.view',
    'incentive.view',
    'incentive.manage',
    'tasks.view',
    'activities.view',
    'inventory.view',
    'inventory.create',
    'inventory.edit',
    'inventory.adjust',
    'inventory.delete',
    'inventory.purchase',
    'inventory.export',
    'inventory.warehouses',
    'inventory.mixer',
    'accounting.view',
    'accounting.create',
    'accounting.edit',
    'accounting.export',
    'accounting.manage',
    'reports.view',
    'reports.export',
    'users.view',
    'users.manage',
    'users.invite',
    'roles.view',
    'settings.view',
    'settings.manage',
    'brand.view',
    'brand.manage',
    'billing.view',
    'billing.manage',
    'security.view',
    'security.manage',
    'courier.view',
    'courier.manage',
    'support.view',
    'support.create',
    'support.manage',
    'coupons.view',
    'coupons.manage',
    'recycle.view',
    'recycle.manage',
    'knowledge.view',
    'knowledge.manage',
    'notifications.view',
    'notifications.failed_login',
    'notifications.system',
    'notifications.low_stock',
    'notifications.overdue_followup',
    'notifications.courier_update',
    'notifications.ticket',
    'notifications.payment_due',
  ],
  team_leader: [
    'dashboard.view',
    'dashboard.widget.orders',
    'dashboard.widget.leads',
    'dashboard.widget.team',
    'contacts.view',
    'leads.view',
    'leads.assign',
    'deals.view',
    'pipeline.view',
    'orders.view',
    'orders.assign',
    'orders.confirm',
    'incentive.view',
    'tasks.view',
    'tasks.assign',
    'activities.view',
    'activities.create',
    'inventory.view',
    'inventory.adjust',
    'reports.view',
    'notifications.view',
    'notifications.system',
    'notifications.overdue_followup',
  ],
  sales_manager: [
    'dashboard.view',
    'dashboard.widget.revenue',
    'dashboard.widget.orders',
    'dashboard.widget.leads',
    'dashboard.widget.team',
    'contacts.view',
    'contacts.create',
    'companies.view',
    'leads.view',
    'leads.create',
    'leads.assign',
    'leads.export',
    'deals.view',
    'deals.create',
    'deals.edit',
    'pipeline.view',
    'orders.view',
    'orders.create',
    'orders.confirm',
    'orders.cancel',
    'orders.assign',
    'orders.export',
    'incentive.view',
    'incentive.manage',
    'tasks.view',
    'tasks.create',
    'activities.view',
    'activities.create',
    'inventory.view',
    'inventory.create',
    'inventory.edit',
    'inventory.adjust',
    'inventory.delete',
    'inventory.purchase',
    'inventory.export',
    'inventory.warehouses',
    'inventory.mixer',
    'accounting.view',
    'accounting.create',
    'accounting.edit',
    'accounting.export',
    'courier.view',
    'courier.manage',
    'support.view',
    'support.create',
    'support.manage',
    'coupons.view',
    'coupons.manage',
    'reports.view',
    'reports.export',
    'notifications.view',
    'notifications.system',
    'notifications.failed_login',
    'notifications.overdue_followup',
    'notifications.courier_update',
    'notifications.ticket',
  ],
  sales_rep: [
    'dashboard.view',
    'dashboard.widget.orders',
    'dashboard.widget.leads',
    'dashboard.widget.team',
    'companies.view',
    'leads.view',
    'leads.create',
    'leads.convert',
    'orders.view',
    'orders.create',
    'orders.confirm',
    'tasks.view',
    'tasks.create',
    'activities.view',
    'activities.create',
    'inventory.view',
    'courier.view',
    'support.view',
    'support.create',
    'coupons.view',
    'notifications.view',
    'notifications.system',
  ],
  marketing_head: [
    'dashboard.view',
    'dashboard.widget.leads',
    'dashboard.widget.marketing',
    'leads.view',
    'leads.create',
    'leads.assign',
    'leads.export',
    'contacts.view',
    'contacts.create',
    'campaigns.view',
    'campaigns.create',
    'campaigns.edit',
    'campaigns.manage_budget',
    'activities.view',
    'activities.create',
    'reports.view',
    'reports.export',
    'tasks.view',
    'tasks.create',
    'notifications.view',
    'notifications.system',
  ],
  support_agent: [
    'dashboard.view',
    'dashboard.widget.orders',
    'contacts.view',
    'contacts.edit',
    'orders.view',
    'orders.cancel',
    'tasks.view',
    'tasks.create',
    'activities.view',
    'activities.create',
    'inventory.view',
    'support.view',
    'support.create',
    'support.manage',
    'notifications.view',
    'notifications.system',
    'notifications.ticket',
  ],
  finance: [
    'dashboard.view',
    'dashboard.widget.revenue',
    'dashboard.widget.orders',
    'orders.view',
    'orders.export',
    'inventory.view',
    'accounting.view',
    'accounting.create',
    'accounting.edit',
    'accounting.export',
    'accounting.manage',
    'reports.view',
    'reports.export',
    'incentive.view',
    'tasks.view',
    'notifications.view',
    'notifications.system',
    'notifications.payment_due',
  ],
  viewer: ['dashboard.view', 'reports.view', 'notifications.view', 'notifications.system'],
};

const PERMISSION_SET = new Set<string>(PERMISSION_CATALOG);

export function isValidPermission(value: string): value is Permission {
  return PERMISSION_SET.has(value);
}

export function getPermissionsForRole(role: UserRole): Permission[] {
  return [...(ROLE_PERMISSIONS[role] ?? [])];
}

export function resolveUserPermissions(user: {
  role: UserRole;
  customRolePermissions?: readonly Permission[];
  permissionGrants?: readonly string[];
  permissionDenies?: readonly string[];
  permissions?: readonly string[];
}): Permission[] {
  const stripPlatform =
    user.role === 'super_admin'
      ? (list: Permission[]) => list
      : (list: Permission[]) =>
          list.filter((p) => !p.startsWith('platform.') && p !== 'dashboard.widget.platform');

  const roleBase = getPermissionsForRole(user.role);
  const customBase = user.customRolePermissions?.length
    ? [...user.customRolePermissions]
    : [];

  // org_admin must not lose newly-added catalog permissions via stale custom roles.
  const mergedBase =
    user.role === 'org_admin'
      ? [...new Set<Permission>([...roleBase, ...customBase])]
      : customBase.length
        ? customBase
        : roleBase;

  const base = stripPlatform(mergedBase);

  const grants = stripPlatform(
    [...(user.permissionGrants ?? []), ...(user.permissions ?? [])].filter(isValidPermission),
  );
  const denies = new Set((user.permissionDenies ?? []).filter(isValidPermission));

  const effective = new Set<Permission>(base);
  for (const grant of grants) {
    effective.add(grant);
  }
  for (const deny of denies) {
    effective.delete(deny);
  }

  return [...effective];
}

export function hasPermission(
  userPermissions: readonly Permission[],
  required: Permission | Permission[],
  match: 'any' | 'all' = 'any',
): boolean {
  const requiredList = Array.isArray(required) ? required : [required];
  if (match === 'all') {
    return requiredList.every((permission) => userPermissions.includes(permission));
  }
  return requiredList.some((permission) => userPermissions.includes(permission));
}
