import type { Permission } from '@laam/types';
import {
  Activity,
  ArrowLeftRight,
  ArrowDownLeft,
  ArrowUpRight,
  BarChart3,
  Blend,
  BookOpen,
  Building2,
  Ban,
  CalendarDays,
  CheckSquare,
  Contact,
  CreditCard,
  GitBranch,
  Handshake,
  LayoutDashboard,
  Megaphone,
  MessageSquare,
  Plug,
  Package,
  RotateCcw,
  Scale,
  Server,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Tag,
  Target,
  Trash2,
  FileUp,
  TrendingDown,
  TrendingUp,
  Truck,
  UserCog,
  Users,
  UsersRound,
  Wallet,
  Zap,
} from 'lucide-react';

import type { UniversalNavGroup } from '@/features/navigation/types/universal-nav';
import { getNavBadgeCounts } from '@/features/navigation/api/nav-badges-api';
import { buildOrdersNav } from '@/features/orders/config/build-orders-nav';

const pv = (p: Permission) => [p] as Permission[];

/** Full app navigation — filtered by effective user permissions. Badges via navBadgesApi. */
export function getUniversalNavRegistry(): UniversalNavGroup[] {
  const badges = getNavBadgeCounts();

  return [
  {
    id: 'main',
    label: 'Main',
    items: [
      {
        id: 'dashboard',
        title: 'Dashboard',
        icon: LayoutDashboard,
        url: '/dashboard',
        permissions: pv('dashboard.view'),
      },
    ],
  },
  {
    id: 'sales',
    label: 'Sales',
    items: [
      {
        id: 'orders',
        title: 'Orders',
        icon: ShoppingCart,
        permissions: pv('orders.view'),
        children: buildOrdersNav().map((queue) => ({
          id: queue.id,
          title: queue.title,
          url: queue.url,
          permissions: queue.permissions,
          badge: queue.badge,
        })),
      },
      {
        id: 'leads',
        title: 'Leads',
        icon: Target,
        url: '/dashboard/leads',
        permissions: pv('leads.view'),
      },
      {
        id: 'pipeline',
        title: 'Pipeline',
        icon: GitBranch,
        url: '/dashboard/pipeline',
        permissions: pv('pipeline.view'),
      },
      {
        id: 'deals',
        title: 'Deals',
        icon: Handshake,
        permissions: pv('deals.view'),
        children: [
          { id: 'deals-all', title: 'All Deals', url: '/dashboard/deals', permissions: pv('deals.view') },
          { id: 'deals-won', title: 'Won', url: '/dashboard/deals?stage=won', permissions: pv('deals.view') },
          { id: 'deals-negotiation', title: 'Negotiation', url: '/dashboard/deals?stage=negotiation', permissions: pv('deals.view') },
        ],
      },
      {
        id: 'customers',
        title: 'Customers',
        icon: Building2,
        url: '/dashboard/customers',
        permissions: pv('companies.view'),
      },
      {
        id: 'contacts',
        title: 'Suppliers & partners',
        icon: Contact,
        url: '/dashboard/contacts',
        permissions: pv('contacts.view'),
      },
    ],
  },
  {
    id: 'marketing',
    label: 'Marketing',
    items: [
      {
        id: 'campaigns',
        title: 'Campaigns',
        icon: Megaphone,
        permissions: pv('campaigns.view'),
        children: [
          { id: 'campaigns-active', title: 'Active', url: '/dashboard/campaigns', permissions: pv('campaigns.view') },
          { id: 'campaigns-budget', title: 'Ad Budget', url: '/dashboard/campaigns?tab=budget', permissions: pv('campaigns.manage_budget') },
          { id: 'campaigns-landing', title: 'Landing Pages', url: '/dashboard/campaigns?tab=landing', permissions: pv('campaigns.edit') },
        ],
      },
      {
        id: 'campaign-roi',
        title: 'Campaign ROI',
        icon: TrendingUp,
        url: '/dashboard/reports?view=campaign',
        permissions: pv('reports.view'),
      },
      {
        id: 'lead-sources',
        title: 'Lead Sources',
        icon: Target,
        url: '/dashboard/reports?view=sources',
        permissions: pv('reports.view'),
      },
    ],
  },
  {
    id: 'inventory',
    label: 'Inventory',
    items: [
      {
        id: 'inv-products',
        title: 'Products',
        icon: Package,
        url: '/dashboard/inventory/products',
        permissions: pv('inventory.view'),
        badge: badges.lowStock,
      },
      {
        id: 'inv-suppliers',
        title: 'Suppliers',
        icon: Truck,
        url: '/dashboard/inventory/suppliers',
        permissions: pv('inventory.view'),
      },
      {
        id: 'inv-purchase',
        title: 'Purchase',
        icon: ShoppingBag,
        url: '/dashboard/inventory/purchase',
        permissions: pv('inventory.purchase'),
      },
      {
        id: 'inv-returns',
        title: 'Purchase returns',
        icon: RotateCcw,
        url: '/dashboard/inventory/purchase-returns',
        permissions: pv('inventory.view'),
      },
      {
        id: 'inv-adjustment',
        title: 'Stock adjustment',
        icon: ArrowLeftRight,
        url: '/dashboard/inventory/adjustment',
        permissions: pv('inventory.adjust'),
      },
      {
        id: 'inv-mixer',
        title: 'Mixer / Production',
        icon: Blend,
        url: '/dashboard/inventory/mixer',
        permissions: pv('inventory.view'),
      },
    ],
  },
  {
    id: 'accounting',
    label: 'Accounting',
    items: [
      {
        id: 'acc-overview',
        title: 'Overview',
        icon: BarChart3,
        url: '/dashboard/accounting/overview',
        permissions: pv('accounting.view'),
      },
      {
        id: 'acc-income',
        title: 'Income',
        icon: TrendingUp,
        url: '/dashboard/accounting/income',
        permissions: pv('accounting.view'),
      },
      {
        id: 'acc-expenses',
        title: 'Expenses',
        icon: TrendingDown,
        url: '/dashboard/accounting/expenses',
        permissions: pv('accounting.view'),
      },
      {
        id: 'acc-ledger',
        title: 'Ledger',
        icon: BookOpen,
        url: '/dashboard/accounting/ledger',
        permissions: pv('accounting.view'),
      },
      {
        id: 'acc-receivables',
        title: 'Receivables',
        icon: ArrowDownLeft,
        url: '/dashboard/accounting/receivables',
        permissions: pv('accounting.view'),
        badge: badges.receivables,
      },
      {
        id: 'acc-payables',
        title: 'Payables',
        icon: ArrowUpRight,
        url: '/dashboard/accounting/payables',
        permissions: pv('accounting.view'),
      },
      {
        id: 'acc-cash',
        title: 'Cash & bank',
        icon: Wallet,
        url: '/dashboard/accounting/cash-bank',
        permissions: pv('accounting.view'),
      },
      {
        id: 'acc-coa',
        title: 'Chart of accounts',
        icon: BookOpen,
        url: '/dashboard/accounting/chart-of-accounts',
        permissions: pv('accounting.manage'),
      },
      {
        id: 'acc-pnl',
        title: 'Profit & loss',
        icon: TrendingUp,
        url: '/dashboard/accounting/profit-loss',
        permissions: pv('accounting.view'),
      },
      {
        id: 'acc-bs',
        title: 'Balance sheet',
        icon: Scale,
        url: '/dashboard/accounting/balance-sheet',
        permissions: pv('accounting.view'),
      },
    ],
  },
  {
    id: 'work',
    label: 'Work',
    items: [
      {
        id: 'activities',
        title: 'Follow Ups',
        icon: Activity,
        url: '/dashboard/followups',
        permissions: pv('activities.view'),
        badge: badges.followups,
      },
      {
        id: 'tasks',
        title: 'Tasks',
        icon: CheckSquare,
        url: '/dashboard/tasks',
        permissions: pv('tasks.view'),
        badge: badges.tasks,
      },
      {
        id: 'automations',
        title: 'Automations',
        icon: Zap,
        url: '/dashboard/automations',
        permissions: pv('settings.manage'),
      },
      {
        id: 'knowledge',
        title: 'Knowledge base',
        icon: BookOpen,
        url: '/dashboard/knowledge',
        permissions: pv('knowledge.view'),
      },
      {
        id: 'calendar',
        title: 'Calendar',
        icon: CalendarDays,
        url: '/dashboard/calendar',
        permissions: pv('dashboard.view'),
      },
      {
        id: 'courier',
        title: 'Courier Hub',
        icon: Truck,
        url: '/dashboard/courier',
        permissions: pv('courier.view'),
        badge: badges.courier,
      },
      {
        id: 'support',
        title: 'Support',
        icon: MessageSquare,
        url: '/dashboard/support',
        permissions: pv('support.view'),
        badge: badges.support,
      },
      {
        id: 'coupons',
        title: 'Coupons',
        icon: Tag,
        url: '/dashboard/coupons',
        permissions: pv('coupons.view'),
      },
    ],
  },
  {
    id: 'team',
    label: 'Team',
    items: [
      {
        id: 'team-agents',
        title: 'Team Agents',
        icon: UsersRound,
        url: '/dashboard/users?view=team',
        permissions: pv('users.view'),
      },
      {
        id: 'team-targets',
        title: 'Team Targets',
        icon: Target,
        url: '/dashboard/reports?view=team-targets',
        permissions: pv('reports.view'),
      },
    ],
  },
  {
    id: 'insights',
    label: 'Insights',
    items: [
      {
        id: 'reports-summary',
        title: 'Reports',
        icon: BarChart3,
        url: '/dashboard/reports?view=summary',
        permissions: pv('reports.view'),
      },
      {
        id: 'reports-sales',
        title: 'Sales',
        icon: TrendingUp,
        url: '/dashboard/reports?view=sales',
        permissions: pv('reports.view'),
      },
      {
        id: 'reports-product',
        title: 'Products',
        icon: Package,
        url: '/dashboard/reports?view=product-sales',
        permissions: pv('reports.view'),
      },
      {
        id: 'reports-agents',
        title: 'Team',
        icon: UsersRound,
        url: '/dashboard/reports?view=agents',
        permissions: pv('reports.view'),
      },
      {
        id: 'reports-meta',
        title: 'Marketing',
        icon: Megaphone,
        url: '/dashboard/reports?view=marketing',
        permissions: pv('reports.view'),
      },
    ],
  },
  {
    id: 'administration',
    label: 'Administration',
    items: [
      {
        id: 'users',
        title: 'Team',
        icon: Users,
        url: '/dashboard/users',
        permissions: ['users.view', 'users.manage'],
      },
      {
        id: 'roles',
        title: 'Roles',
        icon: UserCog,
        url: '/dashboard/settings/roles',
        permissions: ['roles.view', 'roles.manage'],
      },
      {
        id: 'billing',
        title: 'Billing',
        icon: CreditCard,
        url: '/dashboard/billing',
        permissions: pv('billing.view'),
      },
      {
        id: 'security',
        title: 'Blocked list',
        icon: Ban,
        url: '/dashboard/security/blocked',
        permissions: pv('security.view'),
        badge: badges.blocked,
      },
      {
        id: 'settings',
        title: 'Settings',
        icon: Settings,
        url: '/dashboard/settings',
        permissions: ['settings.view', 'settings.manage'],
      },
      {
        id: 'settings-org',
        title: 'Organization',
        icon: Building2,
        url: '/dashboard/settings/organization',
        permissions: pv('settings.view'),
      },
      {
        id: 'settings-integrations',
        title: 'Integrations',
        icon: Plug,
        url: '/dashboard/settings/integrations',
        permissions: pv('settings.manage'),
      },
      {
        id: 'settings-order-statuses',
        title: 'Order Statuses',
        icon: GitBranch,
        url: '/dashboard/settings/order-statuses',
        permissions: pv('settings.manage'),
      },
      {
        id: 'settings-sms',
        title: 'SMS Templates',
        icon: MessageSquare,
        url: '/dashboard/settings/sms-templates',
        permissions: pv('settings.manage'),
      },
      {
        id: 'recycle',
        title: 'Recycle Bin',
        icon: Trash2,
        url: '/dashboard/recycle-bin',
        permissions: pv('recycle.view'),
      },
      {
        id: 'data-import',
        title: 'Bulk import',
        icon: FileUp,
        url: '/dashboard/settings/import',
        permissions: pv('settings.manage'),
      },
    ],
  },
  {
    id: 'platform',
    label: 'Platform',
    items: [
      {
        id: 'organizations',
        title: 'Organizations',
        icon: Building2,
        permissions: pv('platform.view'),
        children: [
          { id: 'orgs-all', title: 'All Tenants', url: '/dashboard/platform?tab=tenants', permissions: pv('platform.view') },
          { id: 'orgs-onboard', title: 'Onboarding', url: '/dashboard/platform?tab=onboarding', permissions: pv('platform.manage') },
        ],
      },
      {
        id: 'system-health',
        title: 'System Health',
        icon: Server,
        permissions: pv('platform.view'),
        children: [
          { id: 'health-overview', title: 'Overview', url: '/dashboard/platform?tab=health', permissions: pv('platform.view') },
          { id: 'health-api', title: 'API Gateway', url: '/dashboard/platform?tab=api', permissions: pv('platform.manage') },
        ],
      },
      {
        id: 'subscriptions',
        title: 'Subscriptions',
        icon: CreditCard,
        permissions: pv('platform.manage'),
        children: [
          { id: 'subs-plans', title: 'Plans', url: '/dashboard/platform?tab=plans', permissions: pv('platform.manage') },
          { id: 'subs-billing', title: 'Billing', url: '/dashboard/platform?tab=billing', permissions: pv('platform.manage') },
        ],
      },
      {
        id: 'platform-home',
        title: 'Platform',
        icon: Shield,
        url: '/dashboard/platform',
        permissions: pv('platform.view'),
      },
    ],
  },
];
}

/** @deprecated Prefer getUniversalNavRegistry() for fresh badges */
export const UNIVERSAL_NAV_REGISTRY = getUniversalNavRegistry();
